title: Jeongwon Yoo # your name (or website title) here
logo: "/images/jungwon.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Junior Developer who is enthusiastic about expanding new experience. I've worked in various fields including magazine, fashion, marketing, and sales over 6 years. Along the way, I fould development is something I can be absorbed in. 
  <br><br>
  I have been self-educated in FE/BE development since November, 2019. I'm currently in the course of Data Scientist training process and looking for more opportunities to work in this field.
  <br><br>
  <a href="https://www.linkedin.com/in/jeongwon-yoo">LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-179642471-1 # your Google Analytics tracking ID here
