title: Jeong won Yoo # your name (or website title) here
logo: "/images/jung.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Junior Developer who is enthusiastic about expanding new experience.
theme: jekyll-theme-minimal
google_analytics: UA-179642471-1 # your Google Analytics tracking ID here
